# Generated by Django 3.1.1 on 2020-11-04 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestConfirm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stockQuantity', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContestProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('NoOfPlayer', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('winnerPrize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('yesterday_closingPrice', models.FloatField()),
                ('Todayclosing_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContestJoinedByUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('winner', models.CharField(default=None, max_length=50, null=True)),
                ('contest_status', models.CharField(default='started', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('contest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contestprofile')),
                ('player', models.ManyToManyField(through='accounts.ContestConfirm', to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='contestconfirm',
            name='Ongoing_contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contestjoinedbyuser'),
        ),
        migrations.AddField(
            model_name='contestconfirm',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='contestconfirm',
            name='stock_selected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.stockprofile'),
        ),
    ]
