# Generated by Django 3.1.1 on 2020-11-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201104_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contest_won',
            field=models.IntegerField(default=0),
        ),
    ]
