# Generated by Django 3.1.1 on 2020-11-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_contest_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='conetest_joined',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestjoinedbyuser',
            name='contest_status',
            field=models.CharField(default='Notstarted', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contest_won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
