# Generated by Django 3.1.1 on 2020-11-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201105_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprofile',
            name='Todayclosing_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='yesterday_closingPrice',
            field=models.FloatField(null=True),
        ),
    ]
