# Generated by Django 3.1.1 on 2020-11-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201106_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprofile',
            name='Todayclosing_price',
            field=models.FloatField(default=150),
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='yesterday_closingPrice',
            field=models.FloatField(default=100),
        ),
    ]
