# Generated by Django 3.1.1 on 2020-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201107_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprofile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
