# Generated by Django 3.1.1 on 2020-11-11 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_stockprofile_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestjoinedbyuser',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='accounts.userprofile'),
        ),
    ]
