# Generated by Django 3.1.1 on 2020-11-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201111_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_contestStarted', models.BooleanField(default=False)),
                ('is_StockPriceUpdated', models.BooleanField(default=False)),
                ('Is_contestFinished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='stockprofile',
            name='is_updated',
        ),
    ]
