# Generated by Django 3.1.1 on 2020-11-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201113_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('Amount', models.FloatField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(max_length=15)),
            ],
        ),
    ]
