# Generated by Django 3.1.1 on 2020-11-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201124_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkall',
            name='is_allChecked',
            field=models.BooleanField(default=False),
        ),
    ]
