# Generated by Django 3.1.1 on 2020-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201128_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='winner',
            new_name='Contest_winner',
        ),
        migrations.AlterField(
            model_name='contestjoinedbyuser',
            name='contest_status',
            field=models.CharField(default='NotStarted', max_length=20),
        ),
    ]
