# Generated by Django 3.1.1 on 2020-11-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201129_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Bonus',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='amount',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
