# Generated by Django 3.1.1 on 2020-11-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201130_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_winner',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='accounts.extendeduser'),
        ),
        migrations.AlterField(
            model_name='contestconfirm',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.extendeduser'),
        ),
        migrations.AlterField(
            model_name='contestjoinedbyuser',
            name='player',
            field=models.ManyToManyField(through='accounts.ContestConfirm', to='accounts.extendedUser'),
        ),
    ]
