# Generated by Django 3.1.1 on 2020-12-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201202_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='user',
            new_name='usr',
        ),
    ]
