# Generated by Django 3.1.1 on 2020-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201202_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='upi_gatewayOfPhone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
